
import java.awt.Cursor;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import org.joda.time.DateTime;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Азизбек Матчанов
 */
public class MainFrame extends javax.swing.JFrame {

    User user;
    Manager manager;
    Date date = new DateTime().toDate(); // todaysdate
    Date dateAfterTwo = new DateTime().plusDays(2).toDate();
    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    Calendar today = Calendar.getInstance();
    Calendar checkInCal = Calendar.getInstance();
    Calendar checkOutCal = Calendar.getInstance();
    Calendar expiryDate = Calendar.getInstance();
    Bill bill;
    int roomNum;
    int numOccupants;
    int row;
    String userName;
   
  /**
     * Creates new form MainFrame
     */
    public MainFrame(User user) {
        initComponents();
        today.setTime(date);
        today.set(Calendar.HOUR_OF_DAY, 0);
        today.set(Calendar.MINUTE, 0);
        today.set(Calendar.SECOND, 0);
        today.set(Calendar.MILLISECOND, 0);
        roomBookingPanel1.setVisible(true);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(false);
        staffManagementPanel2.setVisible(false);
        roomsManagementPanel.setVisible(false);
        guestsManagementPanel.setVisible(false);
        bookingManagementPanel.setVisible(false);
        aboutPanel.setVisible(false);
        checkInCalendar.setDate(date);
        checkOutCalendar.setDate(dateAfterTwo);
        this.user=user;
    }

    javax.swing.table.DefaultTableModel roomTableModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Room Number", "Type of bed", "Type of room","Room rate"
            }
        )   {
                            public boolean isCellEditable(int row, int column)
                        {
                          return false;//This causes all cells to be not editable
                        }
            
        };
    
    javax.swing.table.DefaultTableModel staffManagementTableModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Username", "Password", "Manager", "First Name", "Last Name", "Phone Number", "E-mail", "Country", "City", "Street", "ZIP-Code"
            }
        )   {
                            public boolean isCellEditable(int row, int column)
                        {
                          return false;
                        }
            
        };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userBoxGroup = new javax.swing.ButtonGroup();
        tabsPane = new javax.swing.JLayeredPane();
        staffManagementPane = new javax.swing.JLayeredPane();
        staffManagementPanel1 = new javax.swing.JPanel();
        staffManagementScrollPane = new javax.swing.JScrollPane();
        staffManagementTable = new javax.swing.JTable();
        searchStaffManagementButton = new javax.swing.JLabel();
        showAllStaffManagementButton = new javax.swing.JLabel();
        modifyStaffManagementButton = new javax.swing.JLabel();
        deleteUserStaffManagementButton = new javax.swing.JLabel();
        firstNameStaffManagementLabel1 = new javax.swing.JLabel();
        firstNameStaffManagementField1 = new javax.swing.JTextField();
        lastNameStaffManagementLabel1 = new javax.swing.JLabel();
        lastNameStaffManagementField1 = new javax.swing.JTextField();
        registerUserStaffManagementButton1 = new javax.swing.JLabel();
        staffManagementPanel2 = new javax.swing.JPanel();
        firstNameStaffManagementField2 = new javax.swing.JTextField();
        lastNameStaffManagementField2 = new javax.swing.JTextField();
        countryStaffManagementField2 = new javax.swing.JTextField();
        cityStaffManagementField2 = new javax.swing.JTextField();
        streetStaffManagementField2 = new javax.swing.JTextField();
        zipCodeStaffManagementField2 = new javax.swing.JTextField();
        passwordStaffManagementField2 = new javax.swing.JTextField();
        phoneNumberStaffManagementField2 = new javax.swing.JTextField();
        registerUserStaffManagementButton2 = new javax.swing.JLabel();
        firstNameStaffManagementLabel2 = new javax.swing.JLabel();
        lastNameStaffManagementLabel2 = new javax.swing.JLabel();
        countryStaffManagementLabel2 = new javax.swing.JLabel();
        cityStaffManagementLabel2 = new javax.swing.JLabel();
        streetStaffManagementLabel2 = new javax.swing.JLabel();
        zipCodeStaffManagementLabel2 = new javax.swing.JLabel();
        passwordStaffManagementLabel2 = new javax.swing.JLabel();
        phoneNumberStaffManagementLabel2 = new javax.swing.JLabel();
        emailStaffManagementLabel2 = new javax.swing.JLabel();
        receptionistCheckBox = new javax.swing.JCheckBox();
        managerCheckBox = new javax.swing.JCheckBox();
        emailStaffManagementField2 = new javax.swing.JTextField();
        userNameStaffManagementLabel2 = new javax.swing.JLabel();
        userNameStaffManagementField2 = new javax.swing.JTextField();
        roomBookingPane = new javax.swing.JLayeredPane();
        roomBookingPanel1 = new javax.swing.JPanel();
        adultsNumberBox = new javax.swing.JComboBox<>();
        childrenNumberBox = new javax.swing.JComboBox<>();
        checkOutLabel = new javax.swing.JLabel();
        checkInLabel = new javax.swing.JLabel();
        childrenLabel = new javax.swing.JLabel();
        adultsLabel = new javax.swing.JLabel();
        searchRoomBookingButton = new javax.swing.JLabel();
        checkInCalendar = new com.toedter.calendar.JDateChooser();
        checkOutCalendar = new com.toedter.calendar.JDateChooser();
        roomBookingPanel2 = new javax.swing.JPanel();
        roomsBookingScrollPane = new javax.swing.JScrollPane();
        roomsTable = new javax.swing.JTable();
        bookItButton = new javax.swing.JLabel();
        roomBookingPanel3 = new javax.swing.JPanel();
        firstNameRoomBookingField = new javax.swing.JTextField();
        lastNameRoomBookingField = new javax.swing.JTextField();
        countryRoomBookingField = new javax.swing.JTextField();
        cityRoomBookingField = new javax.swing.JTextField();
        streetRoomBookingField = new javax.swing.JTextField();
        zipCodeRoomBookingField = new javax.swing.JTextField();
        cardNumberRoomBookingField = new javax.swing.JTextField();
        emailRoomBookingField = new javax.swing.JTextField();
        phoneNumberRoomBookingField = new javax.swing.JTextField();
        makeBookingButton = new javax.swing.JLabel();
        expiryMonthRoomBookingCalendar = new com.toedter.calendar.JMonthChooser();
        expiryYearRoomBookingCalendar = new com.toedter.calendar.JYearChooser();
        firstNameRoomBookingLabel = new javax.swing.JLabel();
        lastNameRoomBookingLabel = new javax.swing.JLabel();
        countryRoomBookingLabel = new javax.swing.JLabel();
        cityRoomBookingLabel = new javax.swing.JLabel();
        streetRoomBookingLabel = new javax.swing.JLabel();
        zipCodeRoomBookingLabel = new javax.swing.JLabel();
        cardNumberRoomBookingLabel = new javax.swing.JLabel();
        expiryDateRoomBookingLabel = new javax.swing.JLabel();
        emailRoomBookingLabel = new javax.swing.JLabel();
        creditCardRoomBookingLabel = new javax.swing.JLabel();
        phoneNumberRoomBookingLabel = new javax.swing.JLabel();
        cardHolderNameRoomBookingLabel = new javax.swing.JLabel();
        cardHolderNameRoomBookingField = new javax.swing.JTextField();
        firstNameRoomBookingLabel1 = new javax.swing.JLabel();
        roomsManagementPanel = new javax.swing.JPanel();
        roomsManagementScrollPane = new javax.swing.JScrollPane();
        roomsManagementTable = new javax.swing.JTable();
        searchRoomsManagementButton = new javax.swing.JLabel();
        showRoomsManagementButton = new javax.swing.JLabel();
        modifyRoomsManagementButton = new javax.swing.JLabel();
        firstNameRoomsManagementLabel = new javax.swing.JLabel();
        roomNumberRoomsManagementField = new javax.swing.JTextField();
        guestsManagementPanel = new javax.swing.JPanel();
        guestsScrollPane = new javax.swing.JScrollPane();
        guestsTable = new javax.swing.JTable();
        searchGuestsButton = new javax.swing.JLabel();
        showGuestsButton = new javax.swing.JLabel();
        modifyGuestsButton = new javax.swing.JLabel();
        firstNameGuestsManagementLabel = new javax.swing.JLabel();
        firstNameGuestsManagementField = new javax.swing.JTextField();
        lastNameGuestsManagementLabel = new javax.swing.JLabel();
        lastNameGuestsManagementField = new javax.swing.JTextField();
        bookingManagementPanel = new javax.swing.JPanel();
        aboutPanel = new javax.swing.JPanel();
        aboutPanelBackground = new javax.swing.JLabel();
        roomBookingButton = new javax.swing.JLabel();
        staffManagementButton = new javax.swing.JLabel();
        roomsManagementButton = new javax.swing.JLabel();
        guestsManagementButton = new javax.swing.JLabel();
        bookingManagementButton = new javax.swing.JLabel();
        aboutButton = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        mainBackground = new javax.swing.JLabel();
        blueBackground = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 87, 160));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1285, 745));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        tabsPane.setBackground(new java.awt.Color(0, 87, 167));

        staffManagementPanel1.setBackground(new java.awt.Color(0, 87, 167));
        staffManagementPanel1.setLayout(null);

        staffManagementTable.setModel(staffManagementTableModel);
        staffManagementScrollPane.setViewportView(staffManagementTable);

        staffManagementPanel1.add(staffManagementScrollPane);
        staffManagementScrollPane.setBounds(10, 40, 1010, 350);

        searchStaffManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchButton.png"))); // NOI18N
        searchStaffManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStaffManagementButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchStaffManagementButtonMouseEntered(evt);
            }
        });
        staffManagementPanel1.add(searchStaffManagementButton);
        searchStaffManagementButton.setBounds(700, 410, 320, 60);

        showAllStaffManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showAllButton.png"))); // NOI18N
        showAllStaffManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllStaffManagementButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showAllStaffManagementButtonMouseEntered(evt);
            }
        });
        staffManagementPanel1.add(showAllStaffManagementButton);
        showAllStaffManagementButton.setBounds(350, 490, 320, 60);

        modifyStaffManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modifyButton.png"))); // NOI18N
        staffManagementPanel1.add(modifyStaffManagementButton);
        modifyStaffManagementButton.setBounds(20, 570, 320, 57);

        deleteUserStaffManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteUserButton.png"))); // NOI18N
        deleteUserStaffManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserStaffManagementButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteUserStaffManagementButtonMouseEntered(evt);
            }
        });
        staffManagementPanel1.add(deleteUserStaffManagementButton);
        deleteUserStaffManagementButton.setBounds(350, 570, 320, 57);

        firstNameStaffManagementLabel1.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameStaffManagementLabel1.setForeground(new java.awt.Color(255, 255, 255));
        firstNameStaffManagementLabel1.setText("First Name");
        staffManagementPanel1.add(firstNameStaffManagementLabel1);
        firstNameStaffManagementLabel1.setBounds(10, 390, 220, 40);

        firstNameStaffManagementField1.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameStaffManagementField1.setBorder(null);
        staffManagementPanel1.add(firstNameStaffManagementField1);
        firstNameStaffManagementField1.setBounds(10, 430, 310, 30);

        lastNameStaffManagementLabel1.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameStaffManagementLabel1.setForeground(new java.awt.Color(255, 255, 255));
        lastNameStaffManagementLabel1.setText("Last Name");
        staffManagementPanel1.add(lastNameStaffManagementLabel1);
        lastNameStaffManagementLabel1.setBounds(350, 390, 220, 40);

        lastNameStaffManagementField1.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameStaffManagementField1.setBorder(null);
        staffManagementPanel1.add(lastNameStaffManagementField1);
        lastNameStaffManagementField1.setBounds(350, 430, 310, 30);

        registerUserStaffManagementButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerUserButton.png"))); // NOI18N
        registerUserStaffManagementButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerUserStaffManagementButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerUserStaffManagementButton1MouseEntered(evt);
            }
        });
        staffManagementPanel1.add(registerUserStaffManagementButton1);
        registerUserStaffManagementButton1.setBounds(700, 570, 320, 57);

        staffManagementPane.add(staffManagementPanel1);
        staffManagementPanel1.setBounds(0, 0, 1030, 640);

        staffManagementPanel2.setBackground(new java.awt.Color(0, 87, 167));
        staffManagementPanel2.setLayout(null);

        firstNameStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(firstNameStaffManagementField2);
        firstNameStaffManagementField2.setBounds(50, 100, 280, 30);

        lastNameStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(lastNameStaffManagementField2);
        lastNameStaffManagementField2.setBounds(370, 100, 280, 30);

        countryStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        countryStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(countryStaffManagementField2);
        countryStaffManagementField2.setBounds(50, 190, 220, 30);

        cityStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cityStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(cityStaffManagementField2);
        cityStaffManagementField2.setBounds(300, 190, 210, 30);

        streetStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        streetStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(streetStaffManagementField2);
        streetStaffManagementField2.setBounds(540, 190, 210, 30);

        zipCodeStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        zipCodeStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(zipCodeStaffManagementField2);
        zipCodeStaffManagementField2.setBounds(780, 190, 170, 30);

        passwordStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        passwordStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(passwordStaffManagementField2);
        passwordStaffManagementField2.setBounds(300, 370, 210, 30);

        phoneNumberStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        phoneNumberStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(phoneNumberStaffManagementField2);
        phoneNumberStaffManagementField2.setBounds(330, 280, 240, 30);

        registerUserStaffManagementButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerButton.png"))); // NOI18N
        registerUserStaffManagementButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerUserStaffManagementButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerUserStaffManagementButton2MouseEntered(evt);
            }
        });
        staffManagementPanel2.add(registerUserStaffManagementButton2);
        registerUserStaffManagementButton2.setBounds(350, 490, 320, 60);

        firstNameStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        firstNameStaffManagementLabel2.setText("First Name");
        staffManagementPanel2.add(firstNameStaffManagementLabel2);
        firstNameStaffManagementLabel2.setBounds(50, 60, 180, 40);

        lastNameStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        lastNameStaffManagementLabel2.setText("Last Name");
        staffManagementPanel2.add(lastNameStaffManagementLabel2);
        lastNameStaffManagementLabel2.setBounds(370, 60, 180, 40);

        countryStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        countryStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        countryStaffManagementLabel2.setText("Country");
        staffManagementPanel2.add(countryStaffManagementLabel2);
        countryStaffManagementLabel2.setBounds(50, 150, 70, 40);

        cityStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cityStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        cityStaffManagementLabel2.setText("City");
        staffManagementPanel2.add(cityStaffManagementLabel2);
        cityStaffManagementLabel2.setBounds(300, 150, 40, 40);

        streetStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        streetStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        streetStaffManagementLabel2.setText("Street");
        staffManagementPanel2.add(streetStaffManagementLabel2);
        streetStaffManagementLabel2.setBounds(540, 150, 60, 40);

        zipCodeStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        zipCodeStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        zipCodeStaffManagementLabel2.setText("ZIP Code");
        staffManagementPanel2.add(zipCodeStaffManagementLabel2);
        zipCodeStaffManagementLabel2.setBounds(780, 150, 80, 40);

        passwordStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        passwordStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        passwordStaffManagementLabel2.setText("Password");
        staffManagementPanel2.add(passwordStaffManagementLabel2);
        passwordStaffManagementLabel2.setBounds(300, 330, 90, 40);

        phoneNumberStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        phoneNumberStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumberStaffManagementLabel2.setText("Phone Number");
        staffManagementPanel2.add(phoneNumberStaffManagementLabel2);
        phoneNumberStaffManagementLabel2.setBounds(330, 240, 130, 40);

        emailStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        emailStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        emailStaffManagementLabel2.setText("Email");
        staffManagementPanel2.add(emailStaffManagementLabel2);
        emailStaffManagementLabel2.setBounds(50, 240, 50, 40);

        receptionistCheckBox.setBackground(new java.awt.Color(0, 87, 160));
        userBoxGroup.add(receptionistCheckBox);
        receptionistCheckBox.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        receptionistCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        receptionistCheckBox.setText("Receptionist");
        staffManagementPanel2.add(receptionistCheckBox);
        receptionistCheckBox.setBounds(540, 440, 123, 30);

        managerCheckBox.setBackground(new java.awt.Color(0, 87, 160));
        userBoxGroup.add(managerCheckBox);
        managerCheckBox.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        managerCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        managerCheckBox.setText("Manager");
        staffManagementPanel2.add(managerCheckBox);
        managerCheckBox.setBounds(350, 440, 100, 30);

        emailStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        emailStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(emailStaffManagementField2);
        emailStaffManagementField2.setBounds(50, 280, 250, 30);

        userNameStaffManagementLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        userNameStaffManagementLabel2.setForeground(new java.awt.Color(255, 255, 255));
        userNameStaffManagementLabel2.setText("User Name");
        staffManagementPanel2.add(userNameStaffManagementLabel2);
        userNameStaffManagementLabel2.setBounds(50, 330, 100, 40);

        userNameStaffManagementField2.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        userNameStaffManagementField2.setBorder(null);
        staffManagementPanel2.add(userNameStaffManagementField2);
        userNameStaffManagementField2.setBounds(50, 370, 200, 30);

        staffManagementPane.add(staffManagementPanel2);
        staffManagementPanel2.setBounds(0, 0, 1030, 640);

        tabsPane.add(staffManagementPane);
        staffManagementPane.setBounds(0, 0, 1030, 640);

        roomBookingPane.setBackground(new java.awt.Color(0, 87, 167));

        roomBookingPanel1.setBackground(new java.awt.Color(0, 87, 167));
        roomBookingPanel1.setLayout(null);

        adultsNumberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        roomBookingPanel1.add(adultsNumberBox);
        adultsNumberBox.setBounds(330, 240, 120, 30);

        childrenNumberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        roomBookingPanel1.add(childrenNumberBox);
        childrenNumberBox.setBounds(630, 240, 120, 30);

        checkOutLabel.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        checkOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkOutLabel.setText("Check-Out :");
        roomBookingPanel1.add(checkOutLabel);
        checkOutLabel.setBounds(490, 180, 150, 50);

        checkInLabel.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        checkInLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkInLabel.setText("Check-In :");
        roomBookingPanel1.add(checkInLabel);
        checkInLabel.setBounds(210, 180, 130, 50);

        childrenLabel.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        childrenLabel.setForeground(new java.awt.Color(255, 255, 255));
        childrenLabel.setText("Children :");
        roomBookingPanel1.add(childrenLabel);
        childrenLabel.setBounds(510, 230, 130, 50);

        adultsLabel.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        adultsLabel.setForeground(new java.awt.Color(255, 255, 255));
        adultsLabel.setText("Adults :");
        roomBookingPanel1.add(adultsLabel);
        adultsLabel.setBounds(240, 220, 90, 70);

        searchRoomBookingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchButton.png"))); // NOI18N
        searchRoomBookingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchRoomBookingButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchRoomBookingButtonMouseEntered(evt);
            }
        });
        roomBookingPanel1.add(searchRoomBookingButton);
        searchRoomBookingButton.setBounds(350, 400, 320, 60);
        roomBookingPanel1.add(checkInCalendar);
        checkInCalendar.setBounds(330, 190, 120, 30);
        roomBookingPanel1.add(checkOutCalendar);
        checkOutCalendar.setBounds(630, 190, 120, 30);

        roomBookingPane.add(roomBookingPanel1);
        roomBookingPanel1.setBounds(0, 0, 1030, 640);

        roomBookingPanel2.setBackground(new java.awt.Color(0, 87, 167));
        roomBookingPanel2.setLayout(null);

        roomsTable.setModel(roomTableModel);
        roomsBookingScrollPane.setViewportView(roomsTable);

        roomBookingPanel2.add(roomsBookingScrollPane);
        roomsBookingScrollPane.setBounds(20, 30, 1000, 450);

        bookItButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookItButton.png"))); // NOI18N
        bookItButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookItButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookItButtonMouseEntered(evt);
            }
        });
        roomBookingPanel2.add(bookItButton);
        bookItButton.setBounds(370, 520, 316, 60);

        roomBookingPane.add(roomBookingPanel2);
        roomBookingPanel2.setBounds(0, 0, 1030, 640);

        roomBookingPanel3.setBackground(new java.awt.Color(0, 87, 167));
        roomBookingPanel3.setLayout(null);

        firstNameRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameRoomBookingField.setBorder(null);
        roomBookingPanel3.add(firstNameRoomBookingField);
        firstNameRoomBookingField.setBounds(50, 90, 280, 30);

        lastNameRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameRoomBookingField.setBorder(null);
        roomBookingPanel3.add(lastNameRoomBookingField);
        lastNameRoomBookingField.setBounds(370, 90, 280, 30);

        countryRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        countryRoomBookingField.setBorder(null);
        roomBookingPanel3.add(countryRoomBookingField);
        countryRoomBookingField.setBounds(50, 180, 140, 30);

        cityRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cityRoomBookingField.setBorder(null);
        roomBookingPanel3.add(cityRoomBookingField);
        cityRoomBookingField.setBounds(230, 180, 140, 30);

        streetRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        streetRoomBookingField.setBorder(null);
        roomBookingPanel3.add(streetRoomBookingField);
        streetRoomBookingField.setBounds(410, 180, 210, 30);

        zipCodeRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        zipCodeRoomBookingField.setBorder(null);
        roomBookingPanel3.add(zipCodeRoomBookingField);
        zipCodeRoomBookingField.setBounds(660, 180, 140, 30);

        cardNumberRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cardNumberRoomBookingField.setBorder(null);
        roomBookingPanel3.add(cardNumberRoomBookingField);
        cardNumberRoomBookingField.setBounds(50, 410, 260, 30);

        emailRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        emailRoomBookingField.setBorder(null);
        roomBookingPanel3.add(emailRoomBookingField);
        emailRoomBookingField.setBounds(50, 270, 280, 30);

        phoneNumberRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        phoneNumberRoomBookingField.setBorder(null);
        roomBookingPanel3.add(phoneNumberRoomBookingField);
        phoneNumberRoomBookingField.setBounds(370, 270, 230, 30);

        makeBookingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makeBookingButton.png"))); // NOI18N
        makeBookingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makeBookingButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeBookingButtonMouseEntered(evt);
            }
        });
        roomBookingPanel3.add(makeBookingButton);
        makeBookingButton.setBounds(360, 520, 320, 60);
        roomBookingPanel3.add(expiryMonthRoomBookingCalendar);
        expiryMonthRoomBookingCalendar.setBounds(650, 410, 100, 30);
        roomBookingPanel3.add(expiryYearRoomBookingCalendar);
        expiryYearRoomBookingCalendar.setBounds(750, 410, 50, 30);

        firstNameRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        firstNameRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameRoomBookingLabel.setText("* must be filled in gaps");
        roomBookingPanel3.add(firstNameRoomBookingLabel);
        firstNameRoomBookingLabel.setBounds(50, 460, 140, 40);

        lastNameRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameRoomBookingLabel.setText("Last Name *");
        roomBookingPanel3.add(lastNameRoomBookingLabel);
        lastNameRoomBookingLabel.setBounds(370, 50, 130, 40);

        countryRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        countryRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        countryRoomBookingLabel.setText("Country *");
        roomBookingPanel3.add(countryRoomBookingLabel);
        countryRoomBookingLabel.setBounds(50, 140, 90, 40);

        cityRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cityRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        cityRoomBookingLabel.setText("City ");
        roomBookingPanel3.add(cityRoomBookingLabel);
        cityRoomBookingLabel.setBounds(230, 140, 60, 40);

        streetRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        streetRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        streetRoomBookingLabel.setText("Street");
        roomBookingPanel3.add(streetRoomBookingLabel);
        streetRoomBookingLabel.setBounds(410, 140, 60, 40);

        zipCodeRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        zipCodeRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        zipCodeRoomBookingLabel.setText("ZIP Code");
        roomBookingPanel3.add(zipCodeRoomBookingLabel);
        zipCodeRoomBookingLabel.setBounds(660, 140, 80, 40);

        cardNumberRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cardNumberRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberRoomBookingLabel.setText("Card Number *");
        roomBookingPanel3.add(cardNumberRoomBookingLabel);
        cardNumberRoomBookingLabel.setBounds(50, 370, 180, 40);

        expiryDateRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        expiryDateRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        expiryDateRoomBookingLabel.setText("Expiry Date *");
        roomBookingPanel3.add(expiryDateRoomBookingLabel);
        expiryDateRoomBookingLabel.setBounds(650, 370, 180, 40);

        emailRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        emailRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailRoomBookingLabel.setText("Email *");
        roomBookingPanel3.add(emailRoomBookingLabel);
        emailRoomBookingLabel.setBounds(50, 230, 80, 40);

        creditCardRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        creditCardRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        creditCardRoomBookingLabel.setText("Credit Card:");
        roomBookingPanel3.add(creditCardRoomBookingLabel);
        creditCardRoomBookingLabel.setBounds(50, 330, 180, 40);

        phoneNumberRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        phoneNumberRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumberRoomBookingLabel.setText("Phone Number");
        roomBookingPanel3.add(phoneNumberRoomBookingLabel);
        phoneNumberRoomBookingLabel.setBounds(370, 230, 120, 40);

        cardHolderNameRoomBookingLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cardHolderNameRoomBookingLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardHolderNameRoomBookingLabel.setText("Card Holder Name *");
        roomBookingPanel3.add(cardHolderNameRoomBookingLabel);
        cardHolderNameRoomBookingLabel.setBounds(350, 370, 180, 40);

        cardHolderNameRoomBookingField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        cardHolderNameRoomBookingField.setBorder(null);
        roomBookingPanel3.add(cardHolderNameRoomBookingField);
        cardHolderNameRoomBookingField.setBounds(350, 410, 260, 30);

        firstNameRoomBookingLabel1.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameRoomBookingLabel1.setForeground(new java.awt.Color(255, 255, 255));
        firstNameRoomBookingLabel1.setText("First Name *");
        roomBookingPanel3.add(firstNameRoomBookingLabel1);
        firstNameRoomBookingLabel1.setBounds(50, 50, 110, 40);

        roomBookingPane.add(roomBookingPanel3);
        roomBookingPanel3.setBounds(0, 0, 1030, 640);

        tabsPane.add(roomBookingPane);
        roomBookingPane.setBounds(0, 0, 1030, 640);

        roomsManagementPanel.setBackground(new java.awt.Color(0, 87, 167));
        roomsManagementPanel.setLayout(null);

        roomsManagementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        roomsManagementScrollPane.setViewportView(roomsManagementTable);

        roomsManagementPanel.add(roomsManagementScrollPane);
        roomsManagementScrollPane.setBounds(10, 100, 690, 400);

        searchRoomsManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchButton.png"))); // NOI18N
        roomsManagementPanel.add(searchRoomsManagementButton);
        searchRoomsManagementButton.setBounds(710, 170, 320, 60);

        showRoomsManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showAllButton.png"))); // NOI18N
        roomsManagementPanel.add(showRoomsManagementButton);
        showRoomsManagementButton.setBounds(710, 240, 320, 60);

        modifyRoomsManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modifyButton.png"))); // NOI18N
        roomsManagementPanel.add(modifyRoomsManagementButton);
        modifyRoomsManagementButton.setBounds(710, 310, 320, 57);

        firstNameRoomsManagementLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameRoomsManagementLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameRoomsManagementLabel.setText("Room Number");
        roomsManagementPanel.add(firstNameRoomsManagementLabel);
        firstNameRoomsManagementLabel.setBounds(710, 90, 220, 40);

        roomNumberRoomsManagementField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        roomNumberRoomsManagementField.setBorder(null);
        roomsManagementPanel.add(roomNumberRoomsManagementField);
        roomNumberRoomsManagementField.setBounds(710, 130, 310, 30);

        tabsPane.add(roomsManagementPanel);
        roomsManagementPanel.setBounds(0, 0, 1030, 640);

        guestsManagementPanel.setBackground(new java.awt.Color(0, 87, 167));
        guestsManagementPanel.setLayout(null);

        guestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        guestsScrollPane.setViewportView(guestsTable);

        guestsManagementPanel.add(guestsScrollPane);
        guestsScrollPane.setBounds(10, 100, 690, 400);

        searchGuestsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchButton.png"))); // NOI18N
        guestsManagementPanel.add(searchGuestsButton);
        searchGuestsButton.setBounds(710, 250, 320, 60);

        showGuestsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showAllButton.png"))); // NOI18N
        guestsManagementPanel.add(showGuestsButton);
        showGuestsButton.setBounds(710, 330, 320, 60);

        modifyGuestsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modifyButton.png"))); // NOI18N
        guestsManagementPanel.add(modifyGuestsButton);
        modifyGuestsButton.setBounds(710, 410, 320, 57);

        firstNameGuestsManagementLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameGuestsManagementLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameGuestsManagementLabel.setText("First Name");
        guestsManagementPanel.add(firstNameGuestsManagementLabel);
        firstNameGuestsManagementLabel.setBounds(710, 90, 220, 40);

        firstNameGuestsManagementField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        firstNameGuestsManagementField.setBorder(null);
        guestsManagementPanel.add(firstNameGuestsManagementField);
        firstNameGuestsManagementField.setBounds(710, 130, 310, 30);

        lastNameGuestsManagementLabel.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameGuestsManagementLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameGuestsManagementLabel.setText("Last Name");
        guestsManagementPanel.add(lastNameGuestsManagementLabel);
        lastNameGuestsManagementLabel.setBounds(710, 160, 220, 40);

        lastNameGuestsManagementField.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lastNameGuestsManagementField.setBorder(null);
        guestsManagementPanel.add(lastNameGuestsManagementField);
        lastNameGuestsManagementField.setBounds(710, 200, 310, 30);

        tabsPane.add(guestsManagementPanel);
        guestsManagementPanel.setBounds(0, 0, 1030, 640);

        bookingManagementPanel.setBackground(new java.awt.Color(0, 87, 167));
        tabsPane.add(bookingManagementPanel);
        bookingManagementPanel.setBounds(0, 0, 1030, 640);

        aboutPanel.setBackground(new java.awt.Color(0, 87, 167));

        aboutPanelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AboutPanel.png"))); // NOI18N
        aboutPanel.add(aboutPanelBackground);

        tabsPane.add(aboutPanel);
        aboutPanel.setBounds(0, 0, 1030, 640);

        getContentPane().add(tabsPane);
        tabsPane.setBounds(240, 70, 1030, 640);

        roomBookingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomBookingButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomBookingButtonMouseEntered(evt);
            }
        });
        getContentPane().add(roomBookingButton);
        roomBookingButton.setBounds(50, 20, 120, 80);

        staffManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffManagementButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staffManagementButtonMouseEntered(evt);
            }
        });
        getContentPane().add(staffManagementButton);
        staffManagementButton.setBounds(30, 130, 170, 80);

        roomsManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsManagementButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomsManagementButtonMouseEntered(evt);
            }
        });
        getContentPane().add(roomsManagementButton);
        roomsManagementButton.setBounds(30, 250, 170, 70);

        guestsManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestsManagementButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guestsManagementButtonMouseEntered(evt);
            }
        });
        getContentPane().add(guestsManagementButton);
        guestsManagementButton.setBounds(30, 360, 170, 60);

        bookingManagementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingManagementButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingManagementButtonMouseEntered(evt);
            }
        });
        getContentPane().add(bookingManagementButton);
        bookingManagementButton.setBounds(30, 470, 160, 70);

        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutButtonMouseEntered(evt);
            }
        });
        getContentPane().add(aboutButton);
        aboutButton.setBounds(70, 570, 80, 50);

        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(60, 650, 100, 40);

        mainBackground.setBackground(new java.awt.Color(0, 87, 167));
        mainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame.png"))); // NOI18N
        mainBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        mainBackground.setMinimumSize(new java.awt.Dimension(1920, 1080));
        mainBackground.setName(""); // NOI18N
        mainBackground.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(mainBackground);
        mainBackground.setBounds(0, -180, 1920, 1080);

        blueBackground.setBackground(new java.awt.Color(0, 87, 167));
        blueBackground.setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(blueBackground);
        blueBackground.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomBookingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomBookingButtonMouseEntered
        roomBookingButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_roomBookingButtonMouseEntered

    private void staffManagementButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffManagementButtonMouseEntered
        staffManagementButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_staffManagementButtonMouseEntered

    private void roomsManagementButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsManagementButtonMouseEntered
        roomsManagementButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_roomsManagementButtonMouseEntered

    private void guestsManagementButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestsManagementButtonMouseEntered
        guestsManagementButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_guestsManagementButtonMouseEntered

    private void bookingManagementButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingManagementButtonMouseEntered
        bookingManagementButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bookingManagementButtonMouseEntered

    private void aboutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseEntered
        aboutButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_aboutButtonMouseEntered

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        logoutButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
           dispose();
            /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
        }
        else {
           
        }
        
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void aboutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseClicked
        roomBookingPanel1.setVisible(false);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(false);
        staffManagementPanel2.setVisible(false);
        roomsManagementPanel.setVisible(false);
        guestsManagementPanel.setVisible(false);
        bookingManagementPanel.setVisible(false);
        aboutPanel.setVisible(true);
    }//GEN-LAST:event_aboutButtonMouseClicked

    private void bookingManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingManagementButtonMouseClicked
        roomBookingPanel1.setVisible(false);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(false);
        staffManagementPanel2.setVisible(false);
        roomsManagementPanel.setVisible(false);
        guestsManagementPanel.setVisible(false);
        bookingManagementPanel.setVisible(true);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_bookingManagementButtonMouseClicked

    private void guestsManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestsManagementButtonMouseClicked
        roomBookingPanel1.setVisible(false);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(false);
        staffManagementPanel2.setVisible(false);
        roomsManagementPanel.setVisible(false);
        guestsManagementPanel.setVisible(true);
        bookingManagementPanel.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_guestsManagementButtonMouseClicked

    private void roomsManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsManagementButtonMouseClicked
        if (user instanceof Manager)
        {
        roomBookingPanel1.setVisible(false);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(false);
        staffManagementPanel2.setVisible(false);
        roomsManagementPanel.setVisible(true);
        guestsManagementPanel.setVisible(false);
        bookingManagementPanel.setVisible(false);
        aboutPanel.setVisible(false);
        
        }
        else 
            JOptionPane.showMessageDialog(null, "To have an access to this option\nlogin as a Manager!");
    }//GEN-LAST:event_roomsManagementButtonMouseClicked

    private void staffManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffManagementButtonMouseClicked
        if (user instanceof Manager)
        {
        roomBookingPanel1.setVisible(false);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(true);
        staffManagementPanel2.setVisible(false);
        roomsManagementPanel.setVisible(false);
        guestsManagementPanel.setVisible(false);
        bookingManagementPanel.setVisible(false);
        aboutPanel.setVisible(false);
        
        }
        else 
            JOptionPane.showMessageDialog(null, "To have an access to this option\nlogin as a Manager!");
    }//GEN-LAST:event_staffManagementButtonMouseClicked

    private void roomBookingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomBookingButtonMouseClicked
        roomBookingPanel1.setVisible(true);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(false);
        staffManagementPanel2.setVisible(false);
        roomsManagementPanel.setVisible(false);
        guestsManagementPanel.setVisible(false);
        bookingManagementPanel.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_roomBookingButtonMouseClicked

    private void searchRoomBookingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchRoomBookingButtonMouseEntered
        searchRoomBookingButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_searchRoomBookingButtonMouseEntered

    private void searchRoomBookingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchRoomBookingButtonMouseClicked
        checkInCal.setTime(checkInCalendar.getDate());
        checkInCal.set(Calendar.HOUR_OF_DAY, 0);
        checkInCal.set(Calendar.MINUTE, 0);
        checkInCal.set(Calendar.SECOND, 0);
        checkInCal.set(Calendar.MILLISECOND, 0);
        checkOutCal.setTime(checkOutCalendar.getDate());
        checkOutCal.set(Calendar.HOUR_OF_DAY, 0);
        checkOutCal.set(Calendar.MINUTE, 0);
        checkOutCal.set(Calendar.SECOND, 0);
        checkOutCal.set(Calendar.MILLISECOND, 0);
        if (    checkInCalendar.getDate()==null ||
                checkOutCalendar.getDate()==null ||
                checkInCal.before(today) ||
                checkOutCal.before(checkInCal)||
                sdf.format(checkInCalendar.getDate()).equals(sdf.format(checkOutCalendar.getDate())))
        {
            JOptionPane.showMessageDialog(null, "Wrong check-in or check-out date! Please enter again ", "Alert", JOptionPane.ERROR_MESSAGE);
            checkInCalendar.setDate(date);
            checkOutCalendar.setDate(dateAfterTwo);
        }
        else {
            
            numOccupants = Integer.parseInt((String)adultsNumberBox.getSelectedItem())+Integer.parseInt((String)childrenNumberBox.getSelectedItem());
            
            Vector <Room> availableRooms=user.CheckRoomAvailability(checkInCalendar.getDate(), checkOutCalendar.getDate(), numOccupants);

            roomBookingPanel1.setVisible(false);
            roomBookingPanel2.setVisible(true);
            roomBookingPanel3.setVisible(false);
            staffManagementPanel1.setVisible(false);
            staffManagementPanel2.setVisible(false);
            roomsManagementPanel.setVisible(false);
            guestsManagementPanel.setVisible(false);
            bookingManagementPanel.setVisible(false);
            aboutPanel.setVisible(false);
            
            for (int i=0;i<availableRooms.size();i++)
                {
                    Object[] row = { null, null, null,null};
                    roomTableModel.addRow(row); 
                    roomsTable.setValueAt(availableRooms.get(i).getRoomNo(), i, 0);
                    roomsTable.setValueAt(availableRooms.get(i).getTypeOfBed(), i, 1);
                    roomsTable.setValueAt(availableRooms.get(i).getTypeOfRoom(), i, 2);
                    roomsTable.setValueAt(availableRooms.get(i).getCost(), i, 3);

                }
        } 
    }//GEN-LAST:event_searchRoomBookingButtonMouseClicked

    private void makeBookingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeBookingButtonMouseEntered
        makeBookingButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_makeBookingButtonMouseEntered

    private void bookItButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookItButtonMouseClicked
        row = roomsTable.getSelectedRow();

        if(row == -1)
        {
            JOptionPane.showMessageDialog(null, "Please select a room before booking it! ", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            roomNum = Integer.parseInt(roomsTable.getModel().getValueAt(row, 0).toString());
            
            int reply = JOptionPane.showConfirmDialog(null, "Client should pay: " 
                    + user.showRoomPrice(checkInCalendar.getDate(), checkOutCalendar.getDate(), (double) roomsTable.getModel().getValueAt(row, 3)) +
                    "$\n Are you sure you want to book the room?", "Room booking", JOptionPane.YES_NO_OPTION);
            
            if (reply == JOptionPane.YES_OPTION) {
                bill = user.generateBill(checkInCalendar.getDate(), checkOutCalendar.getDate() , (double) roomsTable.getModel().getValueAt(row, 3));
                roomBookingPanel1.setVisible(false);
                roomBookingPanel2.setVisible(false);
                roomBookingPanel3.setVisible(true);
                staffManagementPanel1.setVisible(false);
                staffManagementPanel2.setVisible(false);
                roomsManagementPanel.setVisible(false);
                guestsManagementPanel.setVisible(false);
                bookingManagementPanel.setVisible(false);
                aboutPanel.setVisible(false);
            }
            
        }
        
    }//GEN-LAST:event_bookItButtonMouseClicked

    private void makeBookingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeBookingButtonMouseClicked
        
        expiryDate.set(Calendar.HOUR_OF_DAY, 0);
        expiryDate.set(Calendar.MINUTE, 0);
        expiryDate.set(Calendar.SECOND, 0);
        expiryDate.set(Calendar.MILLISECOND, 0); 
        expiryDate.set(Calendar.MONTH, expiryMonthRoomBookingCalendar.getMonth());
        expiryDate.set(Calendar.YEAR, expiryYearRoomBookingCalendar.getYear());
        expiryDate.set(Calendar.DATE, expiryDate.getActualMaximum(Calendar.DATE));
        
        if (expiryDate.before(today))
        {
            JOptionPane.showMessageDialog(null, "Your credit card is already expired or you entered wrong expiry date!", "Alert", JOptionPane.ERROR_MESSAGE);
            expiryMonthRoomBookingCalendar.setMonth(Calendar.getInstance().get(Calendar.MONTH));
            expiryYearRoomBookingCalendar.setYear(Calendar.getInstance().get(Calendar.YEAR));
        }
       
        else {
            if (firstNameRoomBookingField.getText().equals("")||
        lastNameRoomBookingField.getText().equals("")||
        countryRoomBookingField.getText().equals("")||
        emailRoomBookingField.getText().equals("")||
        cardNumberRoomBookingField.getText().equals("")||
        cardHolderNameRoomBookingField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must Fill In All '*' Fields!", "Alert", JOptionPane.ERROR_MESSAGE);    
        }
        
        else {
                    CreditCard creditCard = new CreditCard(cardNumberRoomBookingField.getText(), 
                                                           cardHolderNameRoomBookingField.getText(),
                                                           expiryMonthRoomBookingCalendar.getMonth(),
                                                           expiryYearRoomBookingCalendar.getYear());

                    if(creditCard.getCardNumber()!=null) {
                        user.BookRoom(roomNum, firstNameRoomBookingField.getText(),lastNameRoomBookingField.getText(), 
                                phoneNumberRoomBookingField.getText(),emailRoomBookingField.getText(),
                                countryRoomBookingField.getText(),cityRoomBookingField.getText(),streetRoomBookingField.getText(),
                                zipCodeRoomBookingField.getText(),creditCard, checkInCalendar.getDate(), checkOutCalendar.getDate(), 
                                numOccupants, bill);
                        JOptionPane.showMessageDialog(null, "Successfully booked!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                        roomBookingPanel1.setVisible(true);
                        roomBookingPanel2.setVisible(false);
                        roomBookingPanel3.setVisible(false);
                        staffManagementPanel1.setVisible(false);
                        staffManagementPanel2.setVisible(false);
                        roomsManagementPanel.setVisible(false);
                        guestsManagementPanel.setVisible(false);
                        bookingManagementPanel.setVisible(false);
                        aboutPanel.setVisible(false);
                        checkInCalendar.setDate(null);
                        checkOutCalendar.setDate(null);
                        firstNameRoomBookingField.setText("");
                        lastNameRoomBookingField.setText("");
                        countryRoomBookingField.setText("");
                        cityRoomBookingField.setText("");
                        streetRoomBookingField.setText("");
                        zipCodeRoomBookingField.setText("");
                        emailRoomBookingField.setText("");
                        phoneNumberRoomBookingField.setText("");
                        cardNumberRoomBookingField.setText("");
                        cardHolderNameRoomBookingField.setText("");
                        expiryMonthRoomBookingCalendar.setMonth(Calendar.getInstance().get(Calendar.MONTH));
                        expiryYearRoomBookingCalendar.setYear(Calendar.getInstance().get(Calendar.YEAR));
                        checkInCalendar.setDate(date);
                        checkOutCalendar.setDate(dateAfterTwo);
                        adultsNumberBox.setSelectedIndex(0);
                        childrenNumberBox.setSelectedIndex(0);
                        row = -1;
                    }

                }
        }
    }//GEN-LAST:event_makeBookingButtonMouseClicked

    private void bookItButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookItButtonMouseEntered
        bookItButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bookItButtonMouseEntered

    private void registerUserStaffManagementButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserStaffManagementButton2MouseClicked
        if (firstNameStaffManagementField2.getText().equals("")||
        lastNameStaffManagementField2.getText().equals("")||
        countryStaffManagementField2.getText().equals("")||
        cityStaffManagementField2.getText().equals("")||
        streetStaffManagementField2.getText().equals("")||
        zipCodeStaffManagementField2.getText().equals("")||        
        emailStaffManagementField2.getText().equals("")||
        phoneNumberStaffManagementField2.getText().equals("")||        
        userNameStaffManagementField2.getText().equals("")||
        passwordStaffManagementField2.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null, "You Must Fill In All Fields!", "Alert", JOptionPane.ERROR_MESSAGE); 
        }
       
        else {
            user.registerUser(firstNameStaffManagementField2.getText(), lastNameStaffManagementField2.getText(), phoneNumberStaffManagementField2.getText(), 
                    emailStaffManagementField2.getText(), countryStaffManagementField2.getText(), cityStaffManagementField2.getText(),
                    streetStaffManagementField2.getText(), zipCodeStaffManagementField2.getText(), userNameStaffManagementField2.getText(), 
                    passwordStaffManagementField2.getText(), managerCheckBox.isSelected());
            JOptionPane.showMessageDialog(null, "Successfully registered!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                        roomBookingPanel1.setVisible(false);
                        roomBookingPanel2.setVisible(false);
                        roomBookingPanel3.setVisible(false);
                        staffManagementPanel1.setVisible(true);
                        staffManagementPanel2.setVisible(false);
                        roomsManagementPanel.setVisible(false);
                        guestsManagementPanel.setVisible(false);
                        bookingManagementPanel.setVisible(false);
                        aboutPanel.setVisible(false);
                        firstNameStaffManagementField2.setText("");
                        lastNameStaffManagementField2.setText("");
                        countryStaffManagementField2.setText("");
                        cityStaffManagementField2.setText("");
                        streetStaffManagementField2.setText("");
                        zipCodeStaffManagementField2.setText("");        
                        emailStaffManagementField2.setText("");
                        phoneNumberStaffManagementField2.setText("");        
                        userNameStaffManagementField2.setText("");
                        passwordStaffManagementField2.setText("");
                        managerCheckBox.setSelected(false);
                        receptionistCheckBox.setSelected(false);
                        row = -1;
        }
    }//GEN-LAST:event_registerUserStaffManagementButton2MouseClicked

    private void registerUserStaffManagementButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserStaffManagementButton2MouseEntered
        registerUserStaffManagementButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_registerUserStaffManagementButton2MouseEntered

    private void deleteUserStaffManagementButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserStaffManagementButtonMouseEntered
        deleteUserStaffManagementButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteUserStaffManagementButtonMouseEntered

    private void deleteUserStaffManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserStaffManagementButtonMouseClicked
        if ("admin".equals(user.getUserName())){
            row = staffManagementTable.getSelectedRow();
    
            
        if (row == -1)
        {
            JOptionPane.showMessageDialog(null, "Please select an employee before performing an operation ", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            userName = staffManagementTable.getModel().getValueAt(row, 0).toString();
            
            int reply = JOptionPane.showConfirmDialog(null, "Chosen user will be deleted\n Are you sure you want to perform an operation?", "Deleting user", JOptionPane.YES_NO_OPTION);
            
            if (reply == JOptionPane.YES_OPTION) {
                user.deleteUser(userName);
                showAllStaffManagementButtonMouseClicked(evt);
                JOptionPane.showMessageDialog(null, "The user was successfully deleted!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                row = -1;
            }
            
        }
        
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Only admin can delete user!", "Insufficient permission!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteUserStaffManagementButtonMouseClicked

    private void searchStaffManagementButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStaffManagementButtonMouseEntered
        searchStaffManagementButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_searchStaffManagementButtonMouseEntered

    private void searchStaffManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStaffManagementButtonMouseClicked
        
    }//GEN-LAST:event_searchStaffManagementButtonMouseClicked

    private void showAllStaffManagementButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllStaffManagementButtonMouseEntered
        showAllStaffManagementButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_showAllStaffManagementButtonMouseEntered

    private void showAllStaffManagementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllStaffManagementButtonMouseClicked

        Vector<User> found=user.searchUser(null, null);
        staffManagementTableModel.setRowCount(0);
        for (int i=0;i<found.size();i++)
                {
                    Object[] row = { null, null, null,null};
                    staffManagementTableModel.addRow(row); 
                    staffManagementTable.setValueAt(found.get(i).getUserName(), i, 0);
                    staffManagementTable.setValueAt(found.get(i).getPassword(), i, 1);
                    staffManagementTable.setValueAt(found.get(i).isManager(), i, 2);
                    staffManagementTable.setValueAt(found.get(i).getFirstName(), i, 3);
                    staffManagementTable.setValueAt(found.get(i).getLastName(), i, 4);
                    staffManagementTable.setValueAt(found.get(i).getPhoneNumber(), i, 5);
                    staffManagementTable.setValueAt(found.get(i).getEmail(), i, 6);
                    staffManagementTable.setValueAt(found.get(i).getAddress().getCountry(), i, 7);
                    staffManagementTable.setValueAt(found.get(i).getAddress().getCity(), i, 8);
                    staffManagementTable.setValueAt(found.get(i).getAddress().getStreet(), i, 9);
                    staffManagementTable.setValueAt(found.get(i).getAddress().getZipCode(), i, 10);
                    
                }
    }//GEN-LAST:event_showAllStaffManagementButtonMouseClicked

    private void registerUserStaffManagementButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserStaffManagementButton1MouseClicked
        roomBookingPanel1.setVisible(false);
        roomBookingPanel2.setVisible(false);
        roomBookingPanel3.setVisible(false);
        staffManagementPanel1.setVisible(false);
        staffManagementPanel2.setVisible(true);
        roomsManagementPanel.setVisible(false);
        guestsManagementPanel.setVisible(false);
        bookingManagementPanel.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_registerUserStaffManagementButton1MouseClicked

    private void registerUserStaffManagementButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserStaffManagementButton1MouseEntered
        registerUserStaffManagementButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_registerUserStaffManagementButton1MouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutButton;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel aboutPanelBackground;
    private javax.swing.JLabel adultsLabel;
    private javax.swing.JComboBox<String> adultsNumberBox;
    private javax.swing.JPanel blueBackground;
    private javax.swing.JLabel bookItButton;
    private javax.swing.JLabel bookingManagementButton;
    private javax.swing.JPanel bookingManagementPanel;
    private javax.swing.JTextField cardHolderNameRoomBookingField;
    private javax.swing.JLabel cardHolderNameRoomBookingLabel;
    private javax.swing.JTextField cardNumberRoomBookingField;
    private javax.swing.JLabel cardNumberRoomBookingLabel;
    private com.toedter.calendar.JDateChooser checkInCalendar;
    private javax.swing.JLabel checkInLabel;
    private com.toedter.calendar.JDateChooser checkOutCalendar;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JLabel childrenLabel;
    private javax.swing.JComboBox<String> childrenNumberBox;
    private javax.swing.JTextField cityRoomBookingField;
    private javax.swing.JLabel cityRoomBookingLabel;
    private javax.swing.JTextField cityStaffManagementField2;
    private javax.swing.JLabel cityStaffManagementLabel2;
    private javax.swing.JTextField countryRoomBookingField;
    private javax.swing.JLabel countryRoomBookingLabel;
    private javax.swing.JTextField countryStaffManagementField2;
    private javax.swing.JLabel countryStaffManagementLabel2;
    private javax.swing.JLabel creditCardRoomBookingLabel;
    private javax.swing.JLabel deleteUserStaffManagementButton;
    private javax.swing.JTextField emailRoomBookingField;
    private javax.swing.JLabel emailRoomBookingLabel;
    private javax.swing.JTextField emailStaffManagementField2;
    private javax.swing.JLabel emailStaffManagementLabel2;
    private javax.swing.JLabel expiryDateRoomBookingLabel;
    private com.toedter.calendar.JMonthChooser expiryMonthRoomBookingCalendar;
    private com.toedter.calendar.JYearChooser expiryYearRoomBookingCalendar;
    private javax.swing.JTextField firstNameGuestsManagementField;
    private javax.swing.JLabel firstNameGuestsManagementLabel;
    private javax.swing.JTextField firstNameRoomBookingField;
    private javax.swing.JLabel firstNameRoomBookingLabel;
    private javax.swing.JLabel firstNameRoomBookingLabel1;
    private javax.swing.JLabel firstNameRoomsManagementLabel;
    private javax.swing.JTextField firstNameStaffManagementField1;
    private javax.swing.JTextField firstNameStaffManagementField2;
    private javax.swing.JLabel firstNameStaffManagementLabel1;
    private javax.swing.JLabel firstNameStaffManagementLabel2;
    private javax.swing.JLabel guestsManagementButton;
    private javax.swing.JPanel guestsManagementPanel;
    private javax.swing.JScrollPane guestsScrollPane;
    private javax.swing.JTable guestsTable;
    private javax.swing.JTextField lastNameGuestsManagementField;
    private javax.swing.JLabel lastNameGuestsManagementLabel;
    private javax.swing.JTextField lastNameRoomBookingField;
    private javax.swing.JLabel lastNameRoomBookingLabel;
    private javax.swing.JTextField lastNameStaffManagementField1;
    private javax.swing.JTextField lastNameStaffManagementField2;
    private javax.swing.JLabel lastNameStaffManagementLabel1;
    private javax.swing.JLabel lastNameStaffManagementLabel2;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JLabel mainBackground;
    private javax.swing.JLabel makeBookingButton;
    private javax.swing.JCheckBox managerCheckBox;
    private javax.swing.JLabel modifyGuestsButton;
    private javax.swing.JLabel modifyRoomsManagementButton;
    private javax.swing.JLabel modifyStaffManagementButton;
    private javax.swing.JTextField passwordStaffManagementField2;
    private javax.swing.JLabel passwordStaffManagementLabel2;
    private javax.swing.JTextField phoneNumberRoomBookingField;
    private javax.swing.JLabel phoneNumberRoomBookingLabel;
    private javax.swing.JTextField phoneNumberStaffManagementField2;
    private javax.swing.JLabel phoneNumberStaffManagementLabel2;
    private javax.swing.JCheckBox receptionistCheckBox;
    private javax.swing.JLabel registerUserStaffManagementButton1;
    private javax.swing.JLabel registerUserStaffManagementButton2;
    private javax.swing.JLabel roomBookingButton;
    private javax.swing.JLayeredPane roomBookingPane;
    private javax.swing.JPanel roomBookingPanel1;
    private javax.swing.JPanel roomBookingPanel2;
    private javax.swing.JPanel roomBookingPanel3;
    private javax.swing.JTextField roomNumberRoomsManagementField;
    private javax.swing.JScrollPane roomsBookingScrollPane;
    private javax.swing.JLabel roomsManagementButton;
    private javax.swing.JPanel roomsManagementPanel;
    private javax.swing.JScrollPane roomsManagementScrollPane;
    private javax.swing.JTable roomsManagementTable;
    private javax.swing.JTable roomsTable;
    private javax.swing.JLabel searchGuestsButton;
    private javax.swing.JLabel searchRoomBookingButton;
    private javax.swing.JLabel searchRoomsManagementButton;
    private javax.swing.JLabel searchStaffManagementButton;
    private javax.swing.JLabel showAllStaffManagementButton;
    private javax.swing.JLabel showGuestsButton;
    private javax.swing.JLabel showRoomsManagementButton;
    private javax.swing.JLabel staffManagementButton;
    private javax.swing.JLayeredPane staffManagementPane;
    private javax.swing.JPanel staffManagementPanel1;
    private javax.swing.JPanel staffManagementPanel2;
    private javax.swing.JScrollPane staffManagementScrollPane;
    private javax.swing.JTable staffManagementTable;
    private javax.swing.JTextField streetRoomBookingField;
    private javax.swing.JLabel streetRoomBookingLabel;
    private javax.swing.JTextField streetStaffManagementField2;
    private javax.swing.JLabel streetStaffManagementLabel2;
    private javax.swing.JLayeredPane tabsPane;
    private javax.swing.ButtonGroup userBoxGroup;
    private javax.swing.JTextField userNameStaffManagementField2;
    private javax.swing.JLabel userNameStaffManagementLabel2;
    private javax.swing.JTextField zipCodeRoomBookingField;
    private javax.swing.JLabel zipCodeRoomBookingLabel;
    private javax.swing.JTextField zipCodeStaffManagementField2;
    private javax.swing.JLabel zipCodeStaffManagementLabel2;
    // End of variables declaration//GEN-END:variables
}
